ecommerce/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('registeruser/', views.register_user, name='registeruser'),
    path('loginuser/', views.login_user, name='loginuser'),
    path('logout/', views.logout, name='logout'),
    path('guest_register/',views.guest_register_user,name='guest_register'),
    path('orderhistory/',views.orderhistory,name='orderhistory'),
    path('orderdetails/<order_id>',views.orderdetails,name='orderdetails')

]

ecommerce/address/urls.py
from django.urls import path
from . import views

app_name = 'address'


urlpatterns = [
    path('checkout_address/', views.checkout_address,name='checkout_address'),
    path('checkout_address_reuse/', views.checkout_address_reuse,name='checkout_address_reuse'),
]

ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [

    path('cart/', views.cart_home,name='home'),
    path('cart/update/', views.cart_update,name='update'),
    path('cart/checkout/', views.cart_checkout,name='checkout'),
    path('cart/success/', views.cart_success,name='success'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('front.urls')),
    path('',include('products.urls')),
    path('', include('search.urls',namespace='search')),
    path('', include('accounts.urls',namespace='accounts')),
    path('', include('address.urls',namespace='address')),
    path('',include('cart.urls',namespace='cart')),
    path('',include('billing.urls',namespace='billing')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from decimal import Decimal
from django.db.models.signals import m2m_changed, pre_save, post_save
from django.dispatch import receiver

from accounts.models import UserProfile
from products.models import  TestProduct

# Create your models here.

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            cart_created = False
            cart_obj = qs.first()
            if request.session.get('username') is not None and cart_obj.user is None:
                try:
                    cart_obj.user = UserProfile.objects.get(email=request.session.get("username")).id
                except:
                    cart_obj.user=None

                cart_obj.save()
        else:
            try:
                user =UserProfile.objects.get(email=request.session.get("username"))
                # changes by me
            except:
                user = None
            cart_obj = Cart.objects.new(request,user=user)
            cart_created = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, cart_created

    def new(self, request,user=None):
        user_obj = None
        if user is not None:
            if request.session.get('username'):
                user_obj = user
        return self.model.objects.create(user=user_obj)




class Cart(models.Model):
    user        = models.ForeignKey(UserProfile, null=True, blank=True,on_delete=models.CASCADE)
    products    = models.ManyToManyField(TestProduct, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    objects = CartManager()

    def __str__(self):
        return str(self.id)+str(self.products)

def m2m_updated_cart(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for product in products:
            total += product.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_updated_cart, sender=Cart.products.through)




def pre_save_cart_total_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.10) # 8% tax
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_total_receiver, sender=Cart)

ecommerce/cart/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import LoginForm, GuestForm
from address.models import Address
from orders.models import Order
from products.models import TestProduct
from address.forms import AddressForm

from accounts.models import UserProfile, GuestEmail
from cart.models import Cart
from billing.models import BillingProfile

# Create your views here.
def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    #print(request.session.get('cart_id'))
    return render(request, "cart/cart.html", {"cart": cart_obj})

def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = TestProduct.objects.get(id=product_id)
        except TestProduct.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:home")
        cart_obj, cart_created = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            #added = False
        else:
            cart_obj.products.add(product_obj)  # cart_obj.products.add(product_id)
            #added = True
        request.session['cart_items'] = cart_obj.products.count()

    return redirect(reverse("cart:home"))

def cart_checkout(request):

    cart_obj, cart_created = Cart.objects.new_or_get(request)

    next_url = request.build_absolute_uri
    order_obj = None
    if cart_created or cart_obj.products.count()==0:
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    billing_address_form = AddressForm()
    shipping_address_id = request.session.get('shipping_address_id',None)

    billing_address_id = request.session.get('billing_address_id',None)

    # billing profile is creates or not is checked  up in billing profile model manager
    billing_profile,billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    # for card payemnt
    has_card = False

    if billing_profile is not None:
        if 'username' in request.session or 'guest_email_id' in request.session:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj,order_obj_created = Order.objects.new_or_get(billing_profile,cart_obj)

        if shipping_address_id :
            print("you are here shippping address")
            order_obj.shipping_address = Address.objects.get(id = shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id :
            print("you are here billing address")
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session['billing_address_id']
        if billing_address_id or shipping_address_id:
            order_obj.save()
            #print((order_obj))
        has_card = billing_profile.has_card()

    """if request.method =="POST":
        is_done = order_obj.check_done()  # calling manager method
        if is_done:
            order_obj.mark_paid() # calling manager methods
            request.session['cart_items']=0
            del request.session['cart_id']
            return redirect("cart:success")"""
    if request.method=="POST":
        is_ready = order_obj.check_done()
        if is_ready:
            did_charge, crg_msg = billing_profile.charge(order_obj)
            if did_charge:
                order_obj.mark_paid()  # sort a signal for us
                request.session['cart_items'] = 0
                del request.session['cart_id']
                if not billing_profile.user:
                    '''
                    is this the best spot?
                    '''
                    billing_profile.set_cards_inactive()
                return redirect("cart:success")
            else:
                print(crg_msg)
                return redirect("cart:checkout")





    context = {"title": 'checkout',
               "object": order_obj,
               "form":login_form,
               "guest_form":guest_form,
               'billing_profile':billing_profile,
               "next_url":next_url,
               'billing_address_form':billing_address_form,
               'address_type':'shipping',
               'address_qs':address_qs,
               'has_card':has_card,
               'cart':cart_obj,
               }
    return render(request,'cart/checkout.html',context)


def cart_success(request):
    context={"title":"success"}
    return render(request,'cart/success.html',context)

ecommerce/cart/templates/cart/cart.html
{% extends 'base/base.html' %}
{% block content %}


<h4>My Shopping Bag</h4>

{% if cart.products.exists %}
<div class="row">
    <div class="col-md-6">
<table class="table cart-table">
  <thead>
    <tr>
      <th>#</th>
      <th>Product Name</th>
      <th>Product Price</th>
    </tr>
  </thead>
  <tbody class='cart-body'>
    {% for product in cart.products.all %}
    <tr class='cart-product'>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href=''>{{ product.title }}</a>
          <img src="{{ product.image.url }}" width="50px" height="50px;">
        {% include 'cart/remove-product.html' with product_id=product.id %}
      </td>
      <td>{{ product.price }}</td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="2"></td>
      <td><b>Subtotal</b> &#8377; <span class='cart-subtotal'>{{ cart.subtotal }}</span></td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><b>Total</b> &#8377; <span class='cart-total'>{{ cart.total }}</span></td>
    </tr>

   <tr>
      <td colspan="2"></td>
      <td><a class="btn btn-success" href="{%  url 'cart:checkout' %}">Check Out</a> </td>
    </tr>


  </tbody>
</table>
{% else %}
<p class='lead'>Cart is empty</p>
{% endif %}
    </div>
</div>

{%  endblock %}

ecommerce/cart/templates/cart/checkout.html
{% extends 'base/base.html' %}
{% block content %}





{% if not billing_profile %}

        <div class="row">
            <div class="col-md-6">
                <div style="box-shadow: 10px 10px 10px #aaa; padding:50px;border:1px solid #aaa">


                  <h1> Login </h1>

                  <form method="post" action="{% url 'accounts:loginuser' %}">
                     {% csrf_token %}

                  {{ form }}
                  <br>
                  <input type="hidden" name = "next" value="{{next_url }}" >
                  <button type="submit" class="btn btn-warning btn-large " style="float:right;">Submit</button>


                </form>

              </div>

            </div>


             <div class="col-md-6">
                        <h1> Continue As Guest </h1>

                        <form method="post" action="{% url 'accounts:guest_register' %}">
                         {% csrf_token %}

                        {{ guest_form }}
                        <br>

                        <input type="hidden" name = "next" value="{{next_url }}" >
                        <button type="submit" class="btn btn-warning btn-large " style="float:right;">Submit</button>


                         </form>

             </div>
        </div>






{% else %}
        <div class="row">



                {% if not object.shipping_address  %}
                             <div class="col-md-6">

                                 <p class="lead">Shipping Address</p>
                                <form method="post" action="{% url 'address:checkout_address' %}">
                                    {% csrf_token %}
                                    {{ billing_address_form }}
                                    <br>
                                    {% if address_type %}
                                         <input type="hidden" name = "address_type" value="{{ address_type }}" >
                                    {% endif %}
                                     <input type="hidden" name = "next" value="{{next_url }}" >
                                    <button type="submit" class="btn btn-warning btn-large " style="float:right;">Submit</button>
                                </form>
                             </div>
                            <div class="col-md-6">

                                 {% if address_qs.exists %}
                                <form method="post" action="{% url 'address:checkout_address_reuse' %}">
                                    {% csrf_token %}
                                            {% for address in address_qs %}
                                               <label for='address-{{ address.id }}'>
                                                    <input id='address-{{ address.id }}' type='radio' name='shipping_address' value='{{ address.id }}' />
                                                {{ address.address_line_1 }}
                                                </label><br/>

                                             {% endfor %}
                                    {% if next_url %}
                                                <input type='hidden' name='next' value='{{ next_url }}' />
                                          {% endif %}

                                                <input type='hidden' name='address_type' value='shipping_address' />
                                     <button type='submit' class='btn btn-success'>Use Address</button>
                                </form>
                                {% endif %}


                            </div>
        </div>
                 {% elif not object.billing_address %}
                             <div class="col-md-6">
                             <form method="post" action="{% url 'address:checkout_address' %}">
                                  <p class="lead">Billing Address</p>
                                {% csrf_token %}
                                {{ billing_address_form }}
                                <br>
                                {% if address_type %}
                                 <input type="hidden" name = "address_type" value="billing" >
                                {% endif %}
                                 <input type="hidden" name = "next" value="{{next_url }}" >
                                <button type="submit" class="btn btn-warning btn-large " style="float:right;">Submit</button>
                            </form>
                             </div>
                            <div class="col-md-6">

                                <form method="post" action="{% url 'address:checkout_address_reuse' %}">
                                    {% csrf_token %}

                                        {% for address in address_qs %}
                                                <label for='address-{{ address.id }}'>
                                                    <input id='address-{{ address.id }}' type='radio' name='shipping_address' value='{{ address.id }}' />
                                                {{ address.address_line_1 }}
                                                </label><br/>
                                         {% endfor %}
                                         {% if next_url %}
                                                <input type='hidden' name='next' value='{{ next_url }}' />
                                          {% endif %}

                                                <input type='hidden' name='address_type' value='billing_address' />

                                         <button type='submit' class='btn btn-success'>Use Address</button>
                                </form>





                             </div>
        </div>



                {% else %}
                            {% if not has_card %}
                            <form method="GET" action="/payment_method/">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ next_url }}">
                             <button type="submit" class="btn btn-info"> Add New Card</button>
                            </form>

                            {% else %}

                           <div class="col-md-6">
                            <h3> Finalize Check Out </h3>

                               <table class="table cart-table">
                                  <thead>
                                    <tr>
                                      <th>#</th>
                                      <th>Product Name</th>
                                      <th>Product Price</th>
                                    </tr>
                                  </thead>
                                  <tbody class='cart-body'>
                                    {% for product in cart.products.all %}
                                    <tr class='cart-product'>
                                      <th scope="row">{{ forloop.counter }}</th>
                                      <td><a href=''>{{ product.title }}</a>
                                          <img src="{{ product.image.url }}" width="50px" height="50px;">
                                        {% include 'cart/remove-product.html' with product_id=product.id %}
                                      </td>
                                      <td>{{ product.price }}</td>
                                    </tr>
                                    {% endfor %}



                                  </tbody>
                                </table>

                            <p>Payment Method: {{ billing_profile.default_card }} (<a href="/payment_method/?next={{ next_url }}">Change / Add New Card </a>)</p>



                            <p> Cart Total : {{ object.cart.total }}</p>

                                   {% if object.cart.subtotal <= 1000 %}

                                    <p> Shipping Total : {{ object.shipping_total }} <span style="color:grey;font-size:10px;"> (Shop for {{ object.cart.subtotal|add:"-1000" }} More for  Free shipping)</span></p>
                                    {% else %}
                                    <p>Shipping Total : {{ object.shipping_total }} </p>
                                    {% endif %}

                                <p> Order Total : {{ object.total }} </p>
                            <form method="post" class="form" action="">
                                {% csrf_token %}
                            <button type="submit" class="btn btn-warning btn-large " >Confirm Checkout</button>
                            </form>
                          </div>
                            {% endif %}


                {% endif %}





</div>
{% endif %}

{% endblock %}

ecommerce/cart/templates/cart/remove-product.html
<form class='form-product-ajax' method='POST' action='{% url "cart:update" %}' data-endpoint='' class="form"> {% csrf_token %}
    <input class='cart-item-product-id' type='hidden' name='product_id' value='{{ product_id }}' />
      <button type='submit' class='btn btn-link btn-sm' style="padding:0px;cursor: pointer;">Remove?</button>
    </span>
</form>

ecommerce/cart/templates/cart/success.html
{% extends 'base/base.html' %}
{%  block content %}
<div class='col-md-12  text-center'>
  <h5 class="text-success">Thank you for your order!!!</h5>
</div>
{% endblock %}