ecommerce/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('registeruser/', views.register_user, name='registeruser'),
    path('loginuser/', views.login_user, name='loginuser'),
    path('logout/', views.logout, name='logout'),
    path('guest_register/',views.guest_register_user,name='guest_register'),
    path('orderhistory/',views.orderhistory,name='orderhistory'),
    path('orderdetails/<order_id>',views.orderdetails,name='orderdetails')

]

ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [

    path('cart/', views.cart_home,name='home'),
    path('cart/update/', views.cart_update,name='update'),
    path('cart/checkout/', views.cart_checkout,name='checkout'),
    path('cart/success/', views.cart_success,name='success'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('front.urls')),
    path('',include('products.urls')),
    path('', include('search.urls',namespace='search')),
    path('', include('accounts.urls',namespace='accounts')),
    path('', include('address.urls',namespace='address')),
    path('',include('cart.urls',namespace='cart')),
    path('',include('billing.urls',namespace='billing')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/front/urls.py
from django.urls import path
from . import views

app_name='front'
urlpatterns = [
    path('', views.index,name='home'),
    path('about/', views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    path('login/', views.login_page,name='login'),
    path('register/', views.register_page,name='register'),

]

ecommerce/search/urls.py
from django.urls import path
from . import views
app_name = 'search'
urlpatterns = [
    path('search/', views.search,name='search'),


]

ecommerce/templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <title>{{ title }}</title>

    {% include 'base/css.html' %}

      <body>
    {% include 'base/navbar.html' %}
    {% include 'base/header.html' %}

{% block content %}

  {% endblock %}

    <br><br><br>
     {% include 'base/footer.html' %}

      {% include 'base/js.html' %}

  </body>

</html>

ecommerce/templates/base/css.html
 {% load static %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
 <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<script src="https://js.stripe.com/v3/"></script>

ecommerce/templates/base/footer.html
<div class="row">
        <div class="col-md-12">
          <h1 class="jumbotron display-4 text-center" style="background-color:#10377d; color:#ffeb3b"> Copyright : Integration IT Services Pvt Ltd</h1>
        </div>

      </div>
</div>

ecommerce/templates/base/header.html
      <div class="row">
        <div class="col-md-12">
          <p class="jumbotron display-4 text-center" style="background-color:#10377d; color:#ffeb3b"> PRODUCT REVIEW SYSTEM / E-COMMERCE </p>
        </div>

      </div>

ecommerce/templates/base/js.html
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

ecommerce/templates/base/navbar.html
{% url 'cart:home' as cart_url %}
<div class="container-fluid">
     <div class="row">
         <div class="col-md-12">

<nav class="navbar navbar-expand-lg navbar-light " style="background:#ffeb4e">
  <a class="navbar-brand" href="../">IITS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

          <li class="nav-item active">
        <a class="nav-link" href="{% url 'front:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>

         <li class="nav-item active">
        <a class="nav-link" href="{% url 'front:about' %}">About <span class="sr-only">(current)</span></a>
      </li>
         <li class="nav-item active">
        <a class="nav-link" href="{% url 'front:contact' %}">Contact <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="../productpage">Products <span class="sr-only">(current)</span></a>
      </li>
      {% if 'username' not in request.session %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:loginuser' %}"><span class="glyphicon glyphicon-user"></span>Login <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:registeruser' %}">Register</a>
      </li>
      {% endif %}
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{{ cart_url }}"><span style="margin-top: -10;font-size:8px" class="badge badge-danger">{{ request.session.cart_items }}</span><i class="fa fa-shopping-cart fa-2x"></i> <span class="sr-only">(current)</span></a>
      </li>

     {% if 'username' in request.session %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.session.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">View profile</a>
          <a class="dropdown-item" href="{% url 'accounts:orderhistory' %}">Order History</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
        </div>
      </li>
      {% endif %}
      {% if 'guest_email' in request.session %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.session.guest_email }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out Guest</a>
        </div>
      </li>
      {% endif %}






    </ul>
    <form class="form my-2 my-lg-0 search-form" action="{% url 'search:search' %}">
        <div class="input-group">
      <input class="form-control " type="search" placeholder="Search" aria-label="Search" name="search" value="{{ request.GET.search}}">
        <span class="input-group-btn">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="background:#10377d;">Search</button>
        </span>
        </div>
    </form>
  </div>
</nav>
     </div>
 </div>