ecommerce/billing/urls.py
from django.urls import path
from . import views

app_name = 'billing'


urlpatterns = [

    path('payment_method/', views.payment_method,name='payment-method'),
    path('payment_method_create/', views.payment_method_create, name='payment-method-create'),
    path('updatedefaultcard/',views.updatedefaultcard,name='updatedefaultcard')

]

ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [

    path('cart/', views.cart_home,name='home'),
    path('cart/update/', views.cart_update,name='update'),
    path('cart/checkout/', views.cart_checkout,name='checkout'),
    path('cart/success/', views.cart_success,name='success'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('front.urls')),
    path('',include('products.urls')),
    path('', include('search.urls',namespace='search')),
    path('', include('accounts.urls',namespace='accounts')),
    path('', include('address.urls',namespace='address')),
    path('',include('cart.urls',namespace='cart')),
    path('',include('billing.urls',namespace='billing')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/billing/models.py
from django.db import models


# Create your models here.
from django.db.models.signals import post_save, pre_save

from accounts.models import UserProfile, GuestEmail
# for payement gateway
" import stripe and add your secret test key here"
import stripe
stripe.api_key="sk_test_OvjR2MfvkfBoOelUDfVYfjDr00XOFHZ4hX"
# for payment gateway


class BillingProfileManager(models.Manager):
    def new_or_get(self, request):
        user = None
        if 'username' in request.session:
            user = UserProfile.objects.get(email=request.session['username'])
        guest_email_id = request.session.get('guest_email_id')
        created = False
        obj = None
        if user is not None:
            'logged in user checkout; remember payment details'
            obj, created = self.model.objects.get_or_create(
                            user=user, email=user.email)
        elif guest_email_id is not None:
            'guest user checkout; auto reloads payment details'
            guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
            obj, created = self.model.objects.get_or_create(
                                            email=guest_email_obj.email)
        else:
            pass
        return obj, created


class BillingProfile(models.Model):
    user           = models.OneToOneField(UserProfile,null=True,blank=True,on_delete=models.CASCADE)
    email          = models.EmailField()
    active         = models.BooleanField(default=True)
    timestamp      = models.DateTimeField(auto_now_add=True)
    update         = models.DateTimeField(auto_now=True)

    """ for payment gateway create later"""
    customer_id = models.CharField(max_length=120, null=True, blank=True)
    # customer_id for creating a customer for stripe

    objects = BillingProfileManager()



    def __str__(self):
        return self.email

    """ for payment gateway and payment """

    def get_cards(self):
        cards = Card.objects.filter(billing_profile=self)
        return cards



    def has_card(self):  # instance.has_card
        card_qs = self.get_cards()
        #print("you are here")
        #print(card_qs.exists())
        return card_qs.exists()  # True or False


    def default_card(self):
        default_cards = self.get_cards().filter(active=True, default=True)
        if default_cards.exists():
            return default_cards.first()
        return None

    def set_cards_inactive(self):
        cards_qs = self.get_cards()
        cards_qs.update(active=False)
        return cards_qs.filter(active=True).count()

    """ for charging with card """

    def charge(self, order_obj, card=None):
        return Charge.objects.pay(self, order_obj, card)

""" creating a customer unique customer id for stripe payment """

def billing_profile_created_receiver(sender,instance,*args,**kwargs):
    if not instance.customer_id and instance.email:
        print("ACTUAL API REQUEST Send to stripe/braintree")
        customer = stripe.Customer.create(
            email=instance.email
        )
        """ creates a customer on stripe with your secret api key"""
        print(customer)
        instance.customer_id = customer.id
""" pre save signal to Billing Profile"""
pre_save.connect(billing_profile_created_receiver, sender=BillingProfile)

def user_created_reciever(sender,instance,created,*args,**kwargs):
    if created and instance.email:
        BillingProfile.objects.get_or_create(user=instance,email=instance.email)
post_save.connect(user_created_reciever,sender=UserProfile)


class CardManager(models.Manager):
    def all(self, *args, **kwargs): # ModelKlass.objects.all() --> ModelKlass.objects.filter(active=True)
        return self.get_queryset().filter(active=True)

    def add_new(self, billing_profile, token):
        if token:
            customer = stripe.Customer.retrieve(billing_profile.customer_id)
            stripe_card_response = customer.sources.create(source=token)
            new_card = self.model(
                    billing_profile=billing_profile,
                    stripe_id = stripe_card_response.id,
                    brand = stripe_card_response.brand,
                    country = stripe_card_response.country,
                    exp_month = stripe_card_response.exp_month,
                    exp_year = stripe_card_response.exp_year,
                    last4 = stripe_card_response.last4
                )
            new_card.save()
            return new_card
        return None



class Card(models.Model):
    billing_profile         = models.ForeignKey(BillingProfile,on_delete=models.CASCADE)
    stripe_id               = models.CharField(max_length=120)
    brand                   = models.CharField(max_length=120, null=True, blank=True)
    country                 = models.CharField(max_length=20, null=True, blank=True)
    exp_month               = models.IntegerField(null=True, blank=True)
    exp_year                = models.IntegerField(null=True, blank=True)
    last4                   = models.CharField(max_length=4, null=True, blank=True)
    default                 = models.BooleanField(default=True)
    active                  = models.BooleanField(default=True)
    timestamp               = models.DateTimeField(auto_now_add=True)

    objects = CardManager()

    def __str__(self):
        return "{} {}".format(self.brand, self.last4)




def new_card_post_save_receiver(sender, instance, created, *args, **kwargs):
    if instance.default:
        billing_profile = instance.billing_profile
        qs = Card.objects.filter(billing_profile=billing_profile).exclude(pk=instance.pk)
        qs.update(default=False)


post_save.connect(new_card_post_save_receiver, sender=Card)





class ChargeManager(models.Manager):
    def pay(self, billing_profile, order_obj, card=None): # Charge.objects.pay()
        card_obj = card
        if card_obj is None:
            card_obj = billing_profile.default_card();
        if card_obj is None:
            return False, "No cards available"
        c = stripe.Charge.create(
              amount = int(order_obj.total * 100), # 39.19 --> 3919
              currency = "inr",
              customer =  billing_profile.customer_id,
              source = card_obj.stripe_id,
              metadata={"order_id":order_obj.order_id},
            )
        new_charge_obj = self.model(
                billing_profile = billing_profile,
                stripe_id = c.id,
                paid = c.paid,
                refunded = c.refunded,
                outcome = c.outcome,
                outcome_type = c.outcome['type'],
                seller_message = c.outcome.get('seller_message'),
                risk_level = c.outcome.get('risk_level'),
        )
        new_charge_obj.save()
        return new_charge_obj.paid, new_charge_obj.seller_message


class Charge(models.Model):
    billing_profile         = models.ForeignKey(BillingProfile, on_delete=models.CASCADE)
    stripe_id               = models.CharField(max_length=120)
    paid                    = models.BooleanField(default=False)
    refunded                = models.BooleanField(default=False)
    outcome                 = models.TextField(null=True, blank=True)
    outcome_type            = models.CharField(max_length=120, null=True, blank=True)
    seller_message          = models.CharField(max_length=120, null=True, blank=True)
    risk_level              = models.CharField(max_length=120, null=True, blank=True)
    objects = ChargeManager()

ecommerce/billing/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse, HttpResponse
from django.utils.http import is_safe_url
from django.urls import reverse

from billing.models import BillingProfile, Card

" import stripe and add your secret test key here"
import stripe
stripe.api_key="sk_test_OvjR2MfvkfBoOelUDfVYfjDr00XOFHZ4hX"
STRIPE_PUBLISH_KEY ="pk_test_babMK6n6rBv0q4M5h3wSgrep00CGBokpjM"

# Create your views here.
def payment_method(request):
    """ if 'username' in request.session or 'guest_email_id' in request.session:
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        my_customer_id = billing_profile.customer_id """
    billing_profile,billing_profile_created = BillingProfile.objects.new_or_get(request)
    has_card = None;
    if not billing_profile:
        return redirect("cart:home")
    else:
        try:
            cards = Card.objects.filter(billing_profile=billing_profile,active=True)
            has_card = True
        except:
            has_card= None;

    next_url = None
    next_ = request.GET.get('next')
    #print(next)
    if is_safe_url(next_, request.get_host()):
        next_url = next_
    context={"publish_key":STRIPE_PUBLISH_KEY,
             "next_url": next_url,
             "has_card":has_card,
             "cards":cards,
             }
    return render(request,'billing/payment-method.html',context)

def payment_method_create(request):
    if request.method == "POST" and request.is_ajax():
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        if not billing_profile:
            return HttpResponse({"message": "Cannot find this user"}, status_code=401)
        token = request.POST.get("token")
        if token is not None:
            new_card_obj = Card.objects.add_new(billing_profile, token)
        return JsonResponse({"message": "Success! Your card was added."})
    return HttpResponse("error", status_code=401)


def updatedefaultcard(request):
    if request.method=="POST":
        cardid = request.POST.get("cardid")
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        if not billing_profile:
            return redirect("cart:home")
        else:
            qs = Card.objects.filter(billing_profile=billing_profile).exclude(id=cardid)
            qs.update(default=False)
            card = Card.objects.get(id = cardid)
            card.default= True
            card.save()
    return redirect(reverse("cart:checkout"))

ecommerce/billing/templates/billing/payment-method.html
{% extends 'base/base.html' %}
{% block content %}


<style>

.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}

</style>
<div class="row">
<div class='col-md-6 mx-auto'>
   <h3> Add New Card </h3>
<form  class="payment-form" action="" method="post" id="payment-form" data-next-url ="{% if next_url %}{{ next_url }}{% endif %}" data-token="{{ publish_key }}">
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element" class="StripeElement StripeElement--empty form-control">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>
<br>
  <button class="btn btn-primary">Submit Payment</button>
</form>
</div>
  {% if has_card is not None %}
<div class="col-md-6">

  <h3> Choose from Existing Card </h3>
  <form action="{% url 'billing:updatedefaultcard' %}" method="POST">
    {% csrf_token %}

    {% for card in cards %}
    <input type ="radio" name="cardid" value="{{card.id}}"> {{card}}  {% if card.default%} <span style="color:green">-  Default Card</span> {% endif %}
    <br>

    {% endfor %}

    <br>
     <input type="submit" class="btn btn-success"  value="Change Payment Card">

  </form>
</div>
      {% endif %}
</div>

<script>


var paymentForm = $(".payment-form")
var nextUrl = paymentForm.attr("data-next-url")
if (paymentForm >1){
alert("only one payment is allowed");
paymentForm.css('display',"none")
}
else if (paymentForm ==1){
var pubkey = paymentForm.attr("data-token")
nextUrl = paymentForm.attr("data-next-url")
alert(nextUrl)


}

    // Create a Stripe client.
var stripe = Stripe('{{ publish_key }}');

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

function redirectToNext(nextPath, timeoffset) {
    // body...
    if (nextPath){
    setTimeout(function(){
                window.location = nextPath
            }, timeoffset)
    }
}

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  //var form = document.getElementById('payment-form');
  //var hiddenInput = document.createElement('input');
  //hiddenInput.setAttribute('type', 'hidden');
  //hiddenInput.setAttribute('name', 'stripeToken');
  //hiddenInput.setAttribute('value', token.id);
  //form.appendChild(hiddenInput);

  // Submit the form
  //form.submit();

  var paymentMethodEndpoint = '/payment_method_create/'
    var data = {
        'token': token.id,
        csrfmiddlewaretoken: '{{ csrf_token }}'
    }

    $.ajax({
        data: data,
        url: paymentMethodEndpoint,
        method: "POST",

        success: function(data){


            redirectToNext(nextUrl,1500)

        },
        error: function(error){
            console.log(error)

        }
    })
}
</script>
{%  endblock %}